version: '3'

networks:
  prodnetwork:
    driver: bridge

services:
 nexus:
  build: ./nexus
  ports:
    - "18081:8081"
  networks:
    - prodnetwork

 jenkins:
  build: ./jenkins
  ports:
    - "18080:8080"
  networks:
    - prodnetwork
  # volumes:
  #   - ./data/var/run/docker.sock:/var/run/docker.sock
  #   - ./data/usr/local/bin/docker:/usr/bin/docker
  #   - ./data/opt/jenkins/:/var/lib/jenkins/
  # depends_on:
  #   - nexus
  #   - gitlab
  #   - sonar
  # environment:
  #   - NEXUS_PORT=8081
  #   - SONAR_PORT=9000
  #   - SONAR_DB_PORT=5432
 
#  sonar:
#   build: ./sonar
#   ports:
#    - "19000:9000"
#    - "5432:5432"
#   networks:
#     - prodnetwork
#   depends_on:
#     - sonardb
#   environment:
#    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
#    - SONARQUBE_JDBC_USERNAME=sonar
#    - SONARQUBE_JDBC_PASSWORD=sonar
 
#  sonardb:
#   networks:
#     - prodnetwork
#   image: postgres
#   environment:
#    - POSTGRES_USER=sonar
#    - POSTGRES_PASSWORD=sonar
#   volumes:
#     - ./data/opt/postgres/data:/var/lib/postgresql/data
 
#  gitlab:
#   image: gitlab/gitlab-ce:9.3.11-ce.0
#   restart: always
#   networks:
#     - prodnetwork
#   environment:
#     GITLAB_OMNIBUS_CONFIG: |
#       # external_url 'https://gitlab.example.com'
#       # Add any other gitlab.rb configuration here, each on its own line
#   ports:
#     - "80:80"
#     - "443:443"
#     - "2222:22"
#   volumes:
#     - ./data/opt/gitlab/config:/etc/gitlab
#     - ./data/opt/gitlab/logs:/var/log/gitlab
#     - ./data/opt/gitlab/data:/var/opt/gitlab